name:                secure-logic-programming
version:             0.1.0.0
github:              "fs191/secure-logic-programming"
license:             AllRightsReserved
author:              "Alisa Pankova"
copyright:           "2020 Alisa Pankova"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/secure-logic-programming#readme>

dependencies:
- base >= 4.7 && < 5
- Cabal
- process
- strict
- megaparsec
- containers
- parsec
- syb
- mtl
- text
- uniplate
- optparse-applicative
- semigroups
- split
- hashable
- parser-combinators
- optics
- prettyprinter
# Testing only
# For some reason I get errors in ghcide if these are not in the dependencies
- hspec
- HUnit

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  lpsec:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secure-logic-programming

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secure-logic-programming
    - HUnit
    - hspec
    - hspec-expectations
    - criterion
